### ISSUE TITLE
installation is not clear

### ISSUE THREAD

**Issue by jainpratik163** [AKSarav/Kube-Node-Usage#11]
i download git repo and trying to run lib from release folder but it is not running.
from where we can get python code.

or please update installation steps.

**Comment by everflux** [comment]
You can download prebuilt binaries from this directory: https://github.com/AKSarav/Kube-Node-Usage/tree/main/releases
To build the binaries from source run "./build.sh" and have Go in 1.19+ installed. The artifacts are place in the root directory.

**Comment by GritWins** [comment]
I will update the readme little bit more @jainpratik163   and thanks @everflux  for stepping in and assisting.

**Comment by amilcarrey** [comment]
Hey, same problem here. I also downloaded go to build by myself or trying executing `go main.go [options]`

But still the same issue.  

![image](https://github.com/AKSarav/Kube-Node-Usage/assets/12586268/654e0e87-df51-4398-9d1f-04e1dc82337e)

Am I missing something @SaravEasy ?

**Comment by GritWins** [comment]
This error is due to the Kube Config or connection failure - I can work on the Error part and make it more descriptive. @amilcarrey

**Comment by AKSarav** [comment]
@amilcarrey @jainpratik163  I have updated the Error Messages and the Readme files with a few more details. Please download the latest binaries from the latest release 3.0.1 and try

**Comment by amilcarrey** [comment]
Thanks mate! Works well now, would be greather have a brew installation. If I have time this weekend I will try to open a PR. 
Have a nice weekend!
