### ISSUE TITLE
Add artifacts to .gitignore

### ISSUE THREAD

**Issue by everflux** [AKSarav/Kube-Node-Usage#13]
I think it is best practice to add the build results to .gitignore to prevent accidental commits and repository bloat.
To make discovery of the current artifacts easier they could be attached to a github release and the 'release' folder removed from git. (You may want to rewrite the history to reduce the size of the git repository.)

**Comment by GritWins** [comment]
thanks @everflux  - I will try this

**Comment by AKSarav** [comment]
This is done @everflux  Thanks for the idea - Closing the issue

https://github.com/AKSarav/Kube-Node-Usage/releases/tag/v3.0.1
