### ISSUE TITLE
Var names are incorrect - inmb -> ingb

### ISSUE THREAD

**Issue by et304383** [AKSarav/Kube-Node-Usage#5]
https://github.com/AKSarav/Kube-Node-Usage/blob/main/kube-node-usage.py#L111

Variables ending with `inmb` starting here should be suffixed with `ingb` since you devide the Ki value by 1024 twice, which gives GiB.

**Comment by GritWins** [comment]
I have changed this in the new Go setup - Closing this issue

**Comment by AKSarav** [comment]
This issue is resolved in the newer GO Version
