### ISSUE TITLE
Failed to execute the Kubectl get node command

### ISSUE THREAD

**Issue by treppiesse** [AKSarav/Kube-Node-Usage#9]
Hi,
I got the following error when running command: 

python3 kube-node-usage.py --cpu --sort=usage 

_"Failed to execute the Kubectl get node command"_

Please note that I'm able to successfully execute the command:

_kubectl get nodes_ 

Thanks for your support.
Regards

**Comment by AKSarav** [comment]
This is due to the unavailability or the Kubectl command or configuration issues - With the new release we have completely removed the dependency of Kubectl and relying on only ~/.kube/config file and K8s API - Please try now.

**Comment by treppiesse** [comment]
Hi,
my workstation is a Linux machine 64bit with Ubuntu 18.04 OS and go version  1.10.4 linux/amd64.

I updated my files from your repository and retry again.
Results:

1) Launch ./KubeNodeUsage from release folder  ==> "cannot execute binay file: Exec format Error
2) Try to build the release from my arch with the command ./build.sh ==>  Errors (see also attached screenshot)
main.go:6:2 cannot find package "kubenodeusage/k8s" 
main.go:6:2 cannot find package "kubenodeusage/utils" 
![Cattura](https://github.com/AKSarav/Kube-Node-Usage/assets/109551026/5106caa2-c665-4b62-aa10-8267f951569e)



Any suggestions?
Regards
